services:
  postgres_local:
    container_name: postgres_db
    build:
      context: .
      dockerfile: ./docker/Postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=moddingway
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d moddingway -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/App.Dockerfile
    environment:
      POSTGRES_HOST: postgres_local
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: moddingway
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: ${DEBUG:-false}
      GUILD_ID: ${GUILD_ID}
      MOD_LOGGING_CHANNEL_ID: ${MOD_LOGGING_CHANNEL_ID}
    depends_on:
      postgres_local:
        condition:
          service_healthy
