name: Check Ticket Number in Pull Request Description

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_ticket_in_pr_description:
    runs-on: ubuntu-latest

    steps:
      - name: Check pull request description for ticket number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TICKET_PATTERN="^\s*((T|t)((icket)|(ICKET)):\s*)?([A-Z]+-[0-9]+|NA)\s*$"
          match=false

          pr_description=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r .body)

          readarray -t description_split <<<"${pr_description//'\r\n'/$'\n'}"

          for line in "${description_split[@]}"; do
              if [[ "$line" =~ $TICKET_PATTERN ]]; then
                  echo "The pull request description contains a valid ticket format or 'Ticket: NA'."
                  exit 0
              fi
          done
          
          echo "The pull request description does not contain a valid ticket number or 'Ticket: NA'."
          exit 1
